theme: 'readable'
title: 'GFSC Collective Webring'
baseURL: 'https://geeksforsocialchange.github.io/hugo-webring'

languages:
  en:
    languageName: English
    menu:
      main:
      - name: Home
        url: /
        weight: 1
      - name: Sites
        url: /sites
        weight: 10
      - name: Join
        url: /join
        weight: 20
