theme: 'readable'
title: 'GFSC Collective Webring'
baseURL: 'https://webring.gfsc.studio'

languages:
  en:
    languageName: English
    menu:
      main:
      - name: Home
        url: /
        weight: 1
      - name: Sites
        url: /sites
        weight: 10
      - name: Join
        url: /join
        weight: 20

mediaTypes:
  text/opml:
    suffixes:
    - opml
  application/rdf+xml:
    suffixes:
    - rdf

outputFormats:
  opml:
    isPlainText: true
    mediaType: text/opml
  rdf:
    isPlainText: true
    mediaType: application/rdf+xml
